### ISSUE TITLE
Added internal log4net debug PR

### ISSUE THREAD

**Issue by microknights** [WarBorg/DotNetCoreLog4NetApplication#3]
It now writes out to console, so list the output in this issue.

**Comment by WarBorg** [comment]
cool, I will give it a try thx

**Comment by WarBorg** [comment]
ok found the problem:

```
log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Failed in DoAppend
System.PlatformNotSupportedException: Windows Principal functionality is not supported on this platform.
   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at log4net.Core.LoggingEvent.get_UserName()
   at log4net.Core.LoggingEvent.FixVolatileData(FixFlags flags)
   at log4net.Core.LoggingEvent.set_Fix(FixFlags value)
   at log4net.Appender.BufferingAppenderSkeleton.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
[AdoNetAppender] ErrorCode: GenericFailure. Failed in DoAppend
   at System.Security.Principal.WindowsIdentity.GetCurrent()
   at log4net.Core.LoggingEvent.get_UserName()
   at log4net.Core.LoggingEvent.FixVolatileData(FixFlags flags)
   at log4net.Core.LoggingEvent.set_Fix(FixFlags value)
   at log4net.Appender.BufferingAppenderSkeleton.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
```

**Comment by WarBorg** [comment]
should have been fixed by this commit: 

https://github.com/apache/logging-log4net/commit/1a1f9fad9133177aae661e74730e1c602dc0e470

**Comment by microknights** [comment]
hhmmm yes, there have been som "fixes" in the log4net core library. Made a new PR for downgrading log4net core lib.

**Comment by WarBorg** [comment]
merged it and it works now, should we create an issue on the log4net repo with the problem ?

**Comment by microknights** [comment]
No, they have already a lot of Issues regarding this. The fix is made - so we will just wait for the release :)

**Comment by WarBorg** [comment]
yeap, just saw the PR: https://github.com/apache/logging-log4net/pull/70 

thx for the help
